In [1]:
##!pip3 install torch

In [2]:
##!pip3 install numpy

In [3]:
##!pip3 install nltk

In [4]:
from tira.third_party_integrations import ensure_pyterrier_is_loaded, persist_and_normalize_run
from tira.rest_api_client import Client
import pyterrier as pt

import torch
import torch.nn as nn
from torch.utils.data import DataLoader
from torch.optim import Adam

import numpy as np
import scipy.sparse as sp
from topic_modeling import VAE, Encoder, Decoder, SparseDataset, topic_cos_sim



In [ ]:
ensure_pyterrier_is_loaded()
tira = Client()

# The dataset: the union of the IR Anthology and the ACL Anthology
# This line creates an IRDSDataset object and registers it under the name provided as an argument.
pt_dataset = pt.get_dataset('irds:ir-lab-sose-2024/ir-acl-anthology-20240504-training')

# A (pre-built) PyTerrier index loaded from TIRA
index = tira.pt.index('ir-lab-sose-2024/tira-ir-starter/Index (tira-ir-starter-pyterrier)', pt_dataset)

PyTerrier 0.10.0 has loaded Terrier 5.8 (built by craigm on 2023-11-01 18:05) and terrier-helper 0.0.8

No etc/terrier.properties, using terrier.default.properties for bootstrap configuration.


In [ ]:
# hyperparameters

cuda = False
device = torch.device("cuda" if cuda else "cpu")

#epochs = 10
epochs = 10
#batch_size = 8
batch_size = 8
#learning_rate = 1e-2
learning_rate = 1e-3

In [ ]:
""" # bow
# bow = {'O02-2002' : {'i': 2, 'mixtur': 1, 'adopt': 1, 'exampl': 1, 'featur': 2, 'especi': 1, 'classif': 1, 'requir': 1, 'gener': 1, 'measur': 2, 'idf': 1, 'characterist': 1, 'valu': 2, 'languag': 1, 'vector': 3, 'environ': 1, 'data': 1, 'turn': 1}}


bow = {}
for docid in range(doi.getNumberOfDocuments()):
  for posting in  di.getPostings(doi.getDocumentEntry(docid)):
    docno = meta.getItem("docno", docid)
    if not docno in bow:
      bow[docno]= {}
    termid = posting.getId()
    lee = lex.getLexiconEntry(termid)
    bow[docno][lee.getKey()] = posting.getFrequency()

print(bow["O02-2002"]) """

' # bow\n# bow = {\'O02-2002\' : {\'i\': 2, \'mixtur\': 1, \'adopt\': 1, \'exampl\': 1, \'featur\': 2, \'especi\': 1, \'classif\': 1, \'requir\': 1, \'gener\': 1, \'measur\': 2, \'idf\': 1, \'characterist\': 1, \'valu\': 2, \'languag\': 1, \'vector\': 3, \'environ\': 1, \'data\': 1, \'turn\': 1}}\n\n\nbow = {}\nfor docid in range(doi.getNumberOfDocuments()):\n  for posting in  di.getPostings(doi.getDocumentEntry(docid)):\n    docno = meta.getItem("docno", docid)\n    if not docno in bow:\n      bow[docno]= {}\n    termid = posting.getId()\n    lee = lex.getLexiconEntry(termid)\n    bow[docno][lee.getKey()] = posting.getFrequency()\n\nprint(bow["O02-2002"]) '

In [ ]:
di = index.getDirectIndex()
doi = index.getDocumentIndex()
lex = index.getLexicon()
meta = index.getMetaIndex()

test = True

if test:
  train_size = 64
  val_size = 32
else:
  train_size = int(doi.getNumberOfDocuments() * 0.8)
  val_size = doi.getNumberOfDocuments() - int(doi.getNumberOfDocuments() * 0.8)

bow_sparse = sp.dok_matrix((train_size,len(lex)), dtype=np.int8)
bow_sparse_val = sp.dok_matrix((val_size,len(lex)), dtype=np.int8)

for docid in range(train_size + val_size):
  docno = meta.getItem("docno", docid)
  # if docid == 0:
    # print(docno)
  for posting in  di.getPostings(doi.getDocumentEntry(docid)):
    if posting.getFrequency() > 0:
      termid = posting.getId()
      lee = lex.getLexiconEntry(termid)
      # if docid == 0:
        # print(f"{lee.getKey()} , {termid}")
      if docid < train_size:
        bow_sparse[docid, termid] = posting.getFrequency()
      else:
        bow_sparse_val[docid - train_size, termid] = posting.getFrequency()
      # if docid == 0:
        # print(f"{docid}")
        # print(f"{bow_sparse[docid, termid]}")

bow_sparse = bow_sparse.tocsr()
bow_sparse_val = bow_sparse_val.tocsr()

In [ ]:
#print(bow_sparse[31])
print(bow_sparse.shape)
print(bow_sparse[31].todense().item(117))

print(bow_sparse_val.shape)
print(bow_sparse_val[31].todense().item(557))

(64, 97223)
7
(32, 97223)
4


In [ ]:
"""dim = bow_sparse.shape
device = torch.device(device)
indptr = torch.tensor(bow_sparse.indptr, dtype=torch.int64, device=device)
indices = torch.tensor(bow_sparse.indices, dtype=torch.int64, device=device)
data = torch.tensor(bow_sparse.data, dtype=torch.int8, device=device)

print(dim[0])

idx = 0

obs = torch.zeros((dim[1],), dtype=torch.int8, device=device)
print(obs)
print(len(obs))
print(obs[0])
ind1,ind2 = indptr[idx],indptr[idx+1]
obs[indices[ind1:ind2]] = data[ind1:ind2]
print(obs.shape)
print(obs)"""

'dim = bow_sparse.shape\ndevice = torch.device(device)\nindptr = torch.tensor(bow_sparse.indptr, dtype=torch.int64, device=device)\nindices = torch.tensor(bow_sparse.indices, dtype=torch.int64, device=device)\ndata = torch.tensor(bow_sparse.data, dtype=torch.int8, device=device)\n\nprint(dim[0])\n\nidx = 0\n\nobs = torch.zeros((dim[1],), dtype=torch.int8, device=device)\nprint(obs)\nprint(len(obs))\nprint(obs[0])\nind1,ind2 = indptr[idx],indptr[idx+1]\nobs[indices[ind1:ind2]] = data[ind1:ind2]\nprint(obs.shape)\nprint(obs)'

In [ ]:
train_dataset = SparseDataset(bow_sparse, device)
val_dataset = SparseDataset(bow_sparse_val, device)

train_loader = DataLoader(dataset=train_dataset, batch_size=batch_size, shuffle=True)
val_loader = DataLoader(dataset=val_dataset, batch_size=batch_size, shuffle=True)

In [ ]:
print(train_dataset.__getitem__(0))

tensor([2., 1., 1.,  ..., 0., 0., 0.])


In [ ]:
""" for batch, x in enumerate(train_loader):
    print(batch)
    for doc in x:
        for freq in doc:
            if freq > 0:
                print(freq)
                break;
    break """

' for batch, x in enumerate(train_loader):\n    print(batch)\n    for doc in x:\n        for freq in doc:\n            if freq > 0:\n                print(freq)\n                break;\n    break '

In [ ]:
# more hyperparameters

input_dim  = len(lex)
hidden_dim = 512
latent_dim = 8

# hidden_dim = 16384
# latent_dim = 128


In [ ]:
encoder = Encoder(input_dim=input_dim, hidden_dim=hidden_dim, latent_dim=latent_dim)
decoder = Decoder(latent_dim=latent_dim, hidden_dim = hidden_dim, output_dim = input_dim)

vae = VAE(encoder=encoder, decoder=decoder, device=device).to(device)

In [ ]:
print(vae)

VAE(
  (encoder): Encoder(
    (lin1): Linear(in_features=97223, out_features=512, bias=True)
    (lin2): Linear(in_features=512, out_features=512, bias=True)
    (mean): Linear(in_features=512, out_features=8, bias=True)
    (var): Linear(in_features=512, out_features=8, bias=True)
    (LeakyReLU): LeakyReLU(negative_slope=0.2)
  )
  (decoder): Decoder(
    (lin1): Linear(in_features=8, out_features=512, bias=True)
    (lin2): Linear(in_features=512, out_features=512, bias=True)
    (out): Linear(in_features=512, out_features=97223, bias=True)
    (LeakyReLU): LeakyReLU(negative_slope=0.2)
  )
)


In [ ]:
def loss_function(x, x_hat, mean, log_var):
    logsoftmax = torch.log_softmax(x_hat,dim=1)
    rec_loss = -1.0 * torch.sum(x*logsoftmax)

    kl_div = -0.5 * torch.sum(1 + log_var - mean.pow(2) - log_var.exp())

    return rec_loss + kl_div

optimizer = Adam(vae.parameters(), lr=learning_rate)

In [ ]:
print("VAE training:")
vae.train()

for epoch in range(epochs):
    overall_loss = 0
    for batch, x in enumerate(train_loader):

        x = x.view(batch_size, input_dim)
        x = x.to(device)

        optimizer.zero_grad()

        x_hat, mean, log_var = vae(x)
        
        loss = loss_function(x, x_hat, mean, log_var)
        
        overall_loss += loss.item()
        
        loss.backward()
        optimizer.step()
        
    print(f"Epoch {epoch + 1} :\tAverage Loss: {overall_loss / (batch * batch_size)}")
    
print("VAE training done")

VAE training:
Epoch 1 :	Average Loss: 772.353271484375
Epoch 2 :	Average Loss: 772.3255048479352
Epoch 3 :	Average Loss: 771.7692260742188
Epoch 4 :	Average Loss: 770.9572056361607
Epoch 5 :	Average Loss: 770.9559151785714
Epoch 6 :	Average Loss: 771.041255405971
Epoch 7 :	Average Loss: 770.8846391950335
Epoch 8 :	Average Loss: 771.0286298479352
Epoch 9 :	Average Loss: 771.0865740094866
Epoch 10 :	Average Loss: 770.8393467494419
VAE training done


In [ ]:
vae.eval()

with torch.no_grad():
    for batch, x in enumerate(val_loader):
        x = x.view(batch_size, input_dim)
        x = x.to(device)
        
        x_hat, mean, log_var = vae(x)
        for doc in x_hat:
            print(len(doc))
            print(doc)
            print(vae.inference_theta(doc))
            break

97223
tensor([3.0533e-18, 1.9681e-18, 3.1782e-17,  ..., 7.8412e-22, 1.8986e-21,
        4.6304e-21])
[0.25926107 0.06094712 0.1128213  0.06669614 0.14851014 0.03370682
 0.19721784 0.12083951]
97223
tensor([3.1085e-18, 2.1252e-18, 4.7711e-17,  ..., 1.7223e-21, 2.9354e-21,
        8.0158e-21])
[0.19482163 0.04282981 0.04659067 0.09138741 0.12798983 0.33396128
 0.03579765 0.12662166]
97223
tensor([7.0671e-20, 5.3585e-20, 1.2337e-18,  ..., 2.3188e-23, 5.0110e-23,
        2.1341e-22])
[0.10524561 0.20375174 0.02522157 0.16414607 0.25604492 0.04029632
 0.09690887 0.10838488]
97223
tensor([2.0557e-22, 1.2258e-22, 4.6473e-21,  ..., 1.0828e-26, 3.7348e-26,
        1.2705e-25])
[0.05510388 0.7071533  0.01816019 0.00542881 0.05604247 0.04312894
 0.09078204 0.0242003 ]


In [ ]:

qe = (pt.BatchRetrieve(index, wmodel="BM25") % 10 >> \
      pt.apply.doc_score(lambda doc : topic_cos_sim(doc, index, vae)))

run = qe(pt_dataset.get_topics('text'))

run.head(10)

hi
qid                                             1
docid                                       94858
docno                2004.cikm_conference-2004.47
rank                                            0
score                                   15.681777
query    retrieval system improving effectiveness
Name: 0, dtype: object


AttributeError: module 'pyterrier' has no attribute 'EnglishSnowballStemmer'

In [ ]:
lee = lex.getLexiconEntry("retriev")
print(lee)
termid = lee.getTermId()

term743 Nt=14283 TF=28248 maxTF=2147483647 @{0 6743278 0} TFf=28248


'retriev'